micronaut:
  application:
    name: turboFunicular
---
micronaut:
  security:
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <3>
    oauth2:
      clients:
        github:
          client-id:  '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          scopes:
            - user:email
            - read:user
            - gist
          authorization:
            url: 'https://github.com/login/oauth/authorize'
          token:
            url: 'https://github.com/login/oauth/access_token'
            auth-method: client-secret-post
    endpoints:
      logout:
        get-allowed: true
---
micronaut:
  http:
    services:
      githubv3:
        url: "https://api.github.com"
---
micronaut.router.static-resources.static.paths:
  - classpath:/static

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/funicular
    driverClassName: org.postgresql.Driver
    username: user
    password: secret
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true