micronaut:
  application:
    name: turboFunicular

micronaut.router.static-resources.static.paths:
  - classpath:/static

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/funicular
    driverClassName: org.postgresql.Driver
    username: user
    password: secret
    dialect: POSTGRES
