micronaut:
  application:
    name: turboFunicular

micronaut.router.static-resources.static.paths:
  - classpath:/static

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    dialect: POSTGRES